# Usage : docker stack deploy -c acenter.stack.yml acenter

version: "3"

networks:
    gb-net:
        external: true

services:
    Route:
        image: hub:5000/gb-tengine:2.2.0
        networks:
            - gb-net
        hostname: test_route
        volumes:
            - /var/gb/conf/test/nginx:/etc/nginx/
        ports:
            - "8881:80"
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.labels.type == gb_Trace
            restart_policy:
                    condition: on-failure

    APP_work:
        image: hub:5000/gb-tomcat-jre8:7.0.77
        networks:
            - gb-net
        hostname: test_APP_work
        ports:
            - "8882:8080"
        environment:
            -  JAVA_OPTS=-server -Xms4096m -Xmx6144m -XX:NewSize=256m -XX:MaxNewSize=2048m
        volumes:
            - /var/gb/conf/test/tomcat-conf:/usr/local/tomcat/conf
            - /var/tim/apps/tomcat/test:/usr/local/tomcat/webapps
        deploy:
            replicas: 3
            placement:
                constraints:
                    - node.labels.type == gb_APP
            restart_policy:
                    condition: on-failure
