# tngx-app-android
#
version: "3"
networks:
  gb-net:
    external: true

services:
  tngx-app-android:
    image: hub:5000/gb-tengine:2.2.0
    networks:
      - gb-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == gb_Trace
      restart_policy:
        condition: on-failure
    hostname: tngx-app-android
    volumes:
      - /var/gb/data/fserver/upload/data:/data/upload/data
      - /var/gb/conf/nginx-inner-outer/http_backhost_outer:/usr/local/nginx/conf/http_backhost_outer
      - /var/gb/conf/nginx-inner-app-android/lua:/usr/local/nginx/conf/lua
      - /var/gb/conf/nginx-inner-app-android/http_backhost:/usr/local/nginx/conf/http_backhost
      - /var/gb/conf/nginx-inner-app-android/http_facadehost:/usr/local/nginx/conf/http_facadehost
      - /var/gb/conf/nginx-inner-app-android/tcp_backhost:/usr/local/nginx/conf/tcp_backhost
      - /var/gb/conf/nginx-inner-app-android/tcp_facadehost:/usr/local/nginx/conf/tcp_facadehost
      - /var/gb/logs/tengine/app-android:/data/nginx/logs
