# tngx_outer
#
version: "3"
networks:
  gb-net:
    external: true

services:
  tngx-outer:
    image: hub:5000/gb-tengine:2.2.0
    networks:
      - gb-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == gb_Trace
      restart_policy:
        condition: on-failure
    hostname: tngx-outer
    volumes:
      - /var/gb/conf/nginx-outer/http_backhost:/usr/local/nginx/conf/http_backhost
      - /var/gb/conf/nginx-outer/http_facadehost:/usr/local/nginx/conf/http_facadehost
      - /var/gb/conf/nginx-outer/tcp_backhost:/usr/local/nginx/conf/tcp_backhost
      - /var/gb/conf/nginx-outer/tcp_facadehost:/usr/local/nginx/conf/tcp_facadehost
      - /var/gb/logs/tengine/outer:/data/nginx/logs
