# tngx-msites     "81:80"
# tngx-pcenter    "82:80"
# tngx-tcenter    "83:80"
# tngx-acenter    "84:80"
# tngx-mdcenter   "85:80"
# tngx-boss       "86:80"
# tngx-ccenter    "87:80"
# tngx-rcenter    "89:80"
# tngx-api        "90:80"
# tngx-fserver    "91:80"
# tngx-gather     "92:92" "61:61"  "62:62" "63:63"
# tengine-mobile  "93:80"
# 
version: "3"
networks:
  gb-net:
    external: true

services:
  tngx-test:
    image: hub:5000/gb-tengine:2.2.0
    networks:
      - gb-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == gb_Trace
      restart_policy:
        condition: on-failure
    hostname: tngx-test
    ports:
      - "11180:80"
    volumes:
      - /var/gb/conf/test/nginx/:/usr/local/nginx/conf/http_backhost
      - /var/gb/conf/test/lua:/usr/local/nginx/conf/lua
      - /var/gb/logs/test:/data/nginx/logs


